# Load .devbox
[ -f "$HOME/.devbox" ] && source "$HOME/.devbox"

# Put private environment variables in ~/.devbox-zshrc.local. It means they'll stay out
# of main repository (which may be public, like this one), but
# you'll have access to them in your scripts.
[[ -f ~/.devbox-zshrc.local ]] && source ~/.devbox-zshrc.local

LAPTOPD="$DEVBOXD/laptop"

# if condition is checking if homebrew is installed or not
# `brew shellenv` prints a bunch of shell commands like export PATH=..., export HOMEBREW_PREFIX=..., etc.
# that sets your environment so your shell can “find Homebrew” (and the stuff you install with it) in the right places.
# eval "$( ... )" executes those printed commands in the current shell.
if command -v brew >/dev/null; then
  eval "$(brew shellenv)"
fi

# tell zsh where to store command history
HISTFILE=$HOME/.zhistory

# store last ten thousand history commands
SAVEHIST=10000

# how many histories to keep in memory. For more it will have to read from the disk
HISTSIZE=10000

# Share command history across multiple running zsh sessions
setopt share_history

# Drop duplicates before dropping history while trying to not exceed HISTSIZE value
setopt hist_expire_dups_first

# Don’t record a command if it’s exactly the same as the previous command in history.
# If you run ls then ls again immediately, the second one won’t be added.
# It only ignores consecutive duplicates.
setopt hist_ignore_dups

# keep history unique; keep only the latest occurrence of each command
setopt hist_ignore_all_dups

# When executing history commands like !!, !$, !grep the command will be first expanded
# you will get to see the command before it's executed to avoid cases like I didn't want
# to run that command
setopt hist_verify

# Remap what Up and Down arrows do in Zsh.
# ^[ means the ESC character. So ^[[A is literally: ESC, [, A.
# ^[[A = Up arrow
# ^[[B = Down arrow
bindkey '^[[A' history-search-backward
bindkey '^[[B' history-search-forward

ZSH_AUTOSUGGESTIONS="$HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
ZSH_SYNTAX_HIGHLIGHTING="$HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

eval "$(atuin init zsh)"
eval "$(zoxide init zsh)"
source "$LAPTOPD/zsh/prompt.zshrc"

##### ALIASES #####
alias reload!='. ~/.zshrc'

# GIT aliases
alias gps='git push origin HEAD'
alias gs='git status'
alias gap='git add -p'
alias gc='git commit'
alias gco='git checkout'
alias glg='git lg'
alias glg2='git lg2'
alias gwip='git add . && git commit -m "wip"'
alias aic="aicommits --yes"

# git root
gr() {
  local root
  root="$(git rev-parse --show-toplevel 2>/dev/null)" || return 1
  cd "$root"
}

# Update local branch from the remote, and also clean up remote branches.
# It means if a branch was deleted on the remote (say origin/feature-x), then
# local reference origin/feature-x gets removed too.
alias gpl='git pull --prune'

# prefer eza
if command -v eza >/dev/null; then
  alias ls="eza --icons=always"
  alias ll='eza --classify=auto --color -l --icons=always'
  alias la='eza --classify=auto --color -a -l --icons=always'
else
  alias ls="ls -G" # Fallback to standard macos/linux colors
fi

alias cld="claude"
alias cldd="claude --dangerously-skip-permissions"

# Easier navigation
alias cd..="cd .."
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# open VSCode from the present directory
alias c="code ."

# mv, rm, cp
alias mv='mv -v'
alias rm='rm -i -v'
alias cp='cp -v'
alias h='history'

alias hosts='sudo $EDITOR /etc/hosts'   # yes I occasionally 127.0.0.1 x.com

alias laptop="code $LAPTOPD" # open laptop code

# take me to the laptop directory
alias laptopd="cd $LAPTOPD" # go to laptopd directory
alias dotfilesd="cd $DEVBOXD/dotfiles" # go to dotfiles directory

# neeto repos
alias neetozone="cd ~/code/neetozone"
alias authw="cd ~/code/neetozone/neeto-auth-web"
alias formw="cd ~/code/neetozone/neeto-form-web"
alias calw="cd ~/code/neetozone/neeto-cal-web"
alias chatw="cd ~/code/neetozone/neeto-chat-web"
alias deskw="cd ~/code/neetozone/neeto-desk-web"
alias kbw="cd ~/code/neetozone/neeto-kb-web"
alias quizw="cd ~/code/neetozone/neeto-quiz-web"
alias sitew="cd ~/code/neetozone/neeto-site-web"
alias runnerw="cd ~/code/neetozone/neeto-runner-web"
alias replayw="cd ~/code/neetozone/neeto-replay-web"
alias invoicew="cd ~/code/neetozone/neeto-invoice-web"
alias plannerw="cd ~/code/neetozone/neeto-planner-web"
alias coursew="cd ~/code/neetozone/neeto-course-web"
alias wireframew="cd ~/code/neetozone/neeto-wireframe-web"
alias engagew="cd ~/code/neetozone/neeto-engage-web"
alias crmw="cd ~/code/neetozone/neeto-crm-web"
alias deployw="cd ~/code/neetozone/neeto-deploy-web"
alias ciw="cd ~/code/neetozone/neeto-ci-web"
alias gitw="cd ~/code/neetozone/neeto-git-web"
alias recordw="cd ~/code/neetozone/neeto-record-web"
alias towerw="cd ~/code/neetozone/neeto-tower-web"
alias publishw="cd ~/code/neetozone/neeto-publish-web"
alias playdashw="cd ~/code/neetozone/neeto-playdash-web"
alias codew="cd ~/code/neetozone/neeto-code-web"
alias payw="cd ~/code/neetozone/neeto-pay-web"
alias bugwatchw="cd ~/code/neetozone/neeto-bugwatch-web"

# Away From Keyboard (AFK) - Start screen saver
alias afk="open /System/Library/CoreServices/ScreenSaverEngine.app"

# GRC colorizes logfiles and command output
# https://stackoverflow.com/questions/25183624/grc-bashrc-no-such-file-or-directory
if (( $+commands[grc] )) && (( $+commands[brew] ))
then
    source "$HOMEBREW_PREFIX/etc/grc.bashrc"
fi

# load the compinit function when I first use it.
# -U avoids alias expansion; -z uses zsh-style autoloading.
autoload -Uz compinit

# compinit initializes zsh’s completion system (tab completion).
# It loads completion definitions so things like git <TAB> or brew <TAB> work nicely.
compinit -C

# Put your personal bins early
export PATH="$LAPTOPD/bin:$LAPTOPD/utils:$HOME/.local/bin:$PATH"

export PATH="/opt/homebrew/opt/postgresql@18/bin:$PATH"

# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# tunnelto
export TUNNELTO_INSTALL="$HOME/.tunnelto"
export PATH="$TUNNELTO_INSTALL/bin:$PATH"

# Add installed curl to path
export PATH="/opt/homebrew/opt/curl/bin:$PATH"

# Activate mise last so it can manage tool versions per-directory cleanly
eval "$(mise activate zsh)"

DOTFILESD="$DEVBOXD/dotfiles"

# Put any overriding things in personal dotfiles. Personal dotfiles
# should be sibling to laptop repo and it should have a file calle
# .zshrc. This will always be loaded at the very end so ti can override
# anything in the .zshrc of laptop.
if [ -d "$DOTFILESD" ] && [ -f "$DOTFILESD/.zshrc" ]; then
  source "$DOTFILESD/.zshrc"
fi

